version: '3.7'

networks:
  backend:
    driver: bridge

services:
  database:
    image: postgres:10
    env_file:
      - .env
    ports:
      - 5432:54321
    networks:
      backend:
        aliases:
          - db
  api:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    volumes:
      - ../api:/var/www/api:rw
    ports:
      - 8000:8000
    depends_on:
      - database
    networks:
      backend:
        aliases:
          - api
